defaults: &defaults
  working_directory: ~/releases
  docker:
    - image: circleci/node:8.15.1
version: 2
dependencies:
  override:
    - yarn
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
      - restore_cache:
          keys:
            - assets-{{ .Branch }}-{{ .Revision }}
            - assets-{{ .Branch }}-
            - assets-
      # install git-lfs pre-checkout
      - run: curl -sSL https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && sudo apt-get update && sudo apt-get install -y git-lfs && sudo rm -rf /var/lib/apt/lists/*
      
      - checkout
      
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/releases"
      - save_cache:
          key: assets-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/releases/public/assets/"

  install:
    <<: *defaults
    steps:
      - restore_cache:
        name: Restore Source Cache
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Yarn install"
          command: yarn install  --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Test"
          command: "echo 'who needs tests?' > /dev/null"
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Build app"
          command: yarn build
      - persist_to_workspace:
          root: ~/releases
          paths:
            - dist
            - package.json
  deploy:
    <<: *defaults
    environment:
      - STAGING_BUCKET: s3://dev.globally.ltd
      - PRODUCTION_BUCKET: s3://globally.ltd
      - STAGING_DISTRIBUTION_ID: E2RNC34S3LB4YH
      - PRODUCTION_DISTRIBUTION_ID: E36B2H2DAB37RY
    steps:
      - attach_workspace:
          at: ~/releases
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: 
          name: "Deploy to S3"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy.sh "${PRODUCTION_BUCKET}" "${PRODUCTION_DISTRIBUTION_ID}"
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              scripts/deploy.sh "${STAGING_BUCKET}" "${STAGING_DISTRIBUTION_ID}"
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - test
            - build